### ISSUE TITLE
Import statements, classes, arrays & types. FR.

### ISSUE THREAD

**Issue by m10rten** [tylerlaceby/guide-to-interpreters-series#1]
Import & export are a big deal in code land, was wondering if you were planning on including these in the series.

Same for classes / arrays and types(: String, : Int, etc)

Thanks for these series, it's been very assisting in understanding an interpreter/compiler and how to make one. 

classes:
properties inside classes act as object keys?

```
class Animal {}
```

imports:
importing only from string or with from/select
```
import "./some-file.txt";
import { someFunc } from "./some-other-file.txt";
```

exports:
export functions so they can be imported
```
export func handyFunc () {}
```

types:
only in special file types like file.t.txt
```
const numericVal: int = 123; // or : num / : number
const stringVal: char = "abc"; // or : str / : string
```

arrays:
some variable containing an array
```
const list = [];
const filledList = [1,2,3];
```

etc. etc.

**Comment by m10rten** [comment]
In addition:
```
let truthy = a > 0
```

then truthy is a boolean value

**Comment by m10rten** [comment]
@tlaceby Are you planning on making more updates to this repository?

**Comment by tlaceby** [comment]
Yes I plan on finishing the series however I do not think I will proceed to do anything with OOP, imports, and arrays. Arrays in our interpreter would act almost identically to our other data types present. Just like how a number in our language is a simple wrapper around a javascript primitave, an arrayn would just be a wrapper around a javascript array. 

OOP would be a interesting topic to cover as I think its important in understanding however I just personally dont really want to go that far with this series. I know some people would like it however after the most recent videos that cover functions and closures I think it is possible for followers of the series to be able to figure out how classes would work.

After all a class is basically a blueprint for a custom environment. Just like a function is a blueprint. I would be happy to answer questions regarding these topics in discord however I dont think I will continue the series after the videos that would cover boolean datatypes, loops, if/else statements. 

As for import and export statements I think those are good ideas for any language to impliment and I think that we would want to refactor the language to make them dynamic at runtime unlike the javascript import statement. Making them a fuction call could be quiet useful in making it possible to dynamically call them at runtime.

However if you are struggling with import statements that run before any code is executed I suggest making the language run in more than one step. Having a sweeping phase could ensure that imports and function declarations all get appended to the global scope and then you can execute top level code in the second phase statement by statement.

Hopoefully this clears up what my intentions and plans for the series are. Feel free to contact on discord or by github. Cheers!

**Comment by hueychen27** [comment]
@tlaceby Will strings be added?
